package com.ndgndg91.byfeature.global.exception

enum class ErrorCode(val code: Int) {
    SUCCESS(0),
    INVALID_VALUE(1),
    SERVICE(2),

    EMAIL_REQUIRED(1000),
    TOO_SHORT_EMAIL(1001),
    TOO_LONG_EMAIL(1002),
    INVALID_EMAIL_PATTERN(1003),

    PASSWORD_REQUIRED(2000),
    TOO_SHORT_PASSWORD(2001),
    TOO_LONG_PASSWORD(2002),
    INCLUDE_INVALID_CHARACTER_PASSWORD(2003),
}